name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login tencentyun
      run: docker login --username=${{ secrets.TENCENTYUN_USERNAME }} --password=${{ secrets.TENCENTYUN_PASSWORD }} ccr.ccs.tencentyun.com
      
    - name: Re tag the docker image
      run: pwsh ./docker-image-re-tag.ps1